Update ci-cd-backend.yml

diff --git a/.github/workflows/ci-cd-backend.yml b/.github/workflows/ci-cd-backend.yml
--- a/.github/workflows/ci-cd-backend.yml
+++ b/.github/workflows/ci-cd-backend.yml
@@ -28,19 +28,19 @@ jobs:
     - name: Terraform Init
       run: terraform init
 
-    - name: Import Existing Resources
+    - name: Remove Existing Resources from Terraform State
       run: |
-        terraform import aws_iam_role.lambda_execut_role lambda_execut_role
-        terraform import aws_dynamodb_table.VisitorCounter VisitorCounter
-        # Add additional import commands for other existing resources if needed
+        terraform state rm aws_iam_role.lambda_execut_role || echo "Role not found in state"
+        terraform state rm aws_iam_policy.lambda_dynamo_policy || echo "Policy not found in state"
+        terraform state rm aws_dynamodb_table.VisitorCounter || echo "Table not found in state"
+        terraform state rm aws_lambda_function.visitor_counter_function || echo "Function not found in state"
 
     - name: Import Existing Resources
       run: |
-       terraform import aws_iam_role.lambda_execut_role lambda_execut_role
-       terraform import aws_dynamodb_table.VisitorCounter VisitorCounter
-       terraform import aws_iam_policy.lambda_dynamo_policy lambda_dynamo_policy
-       terraform import aws_lambda_function.visitor_counter_function VisitorCounterFunction
-   
+        terraform import aws_iam_role.lambda_execut_role lambda_execut_role
+        terraform import aws_iam_policy.lambda_dynamo_policy lambda_dynamo_policy
+        terraform import aws_dynamodb_table.VisitorCounter VisitorCounter
+        terraform import aws_lambda_function.visitor_counter_function VisitorCounterFunction
 
     - name: Terraform Plan
       run: terraform plan
@@ -60,4 +60,5 @@ jobs:
     - name: Create CloudFront Invalidation
       run: |
         aws cloudfront create-invalidation --distribution-id E3K9N6AT08YG7J --paths "/*"
+
 
